// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI-powered tool that suggests boots and hats based on the product the user is currently viewing.
 *
 * - aiSuggestedOutfits - A function that suggests outfits based on a product.
 * - AiSuggestedOutfitsInput - The input type for the aiSuggestedOutfits function.
 * - AiSuggestedOutfitsOutput - The return type for the aiSuggestedOutfits function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiSuggestedOutfitsInputSchema = z.object({
  productDescription: z.string().describe('The description of the product the user is currently viewing.'),
});
export type AiSuggestedOutfitsInput = z.infer<typeof AiSuggestedOutfitsInputSchema>;

const AiSuggestedOutfitsOutputSchema = z.object({
  hatSuggestion: z.string().describe('A suggestion for a hat that matches the product.'),
  bootsSuggestion: z.string().describe('A suggestion for boots that match the product.'),
});
export type AiSuggestedOutfitsOutput = z.infer<typeof AiSuggestedOutfitsOutputSchema>;

export async function aiSuggestedOutfits(input: AiSuggestedOutfitsInput): Promise<AiSuggestedOutfitsOutput> {
  return aiSuggestedOutfitsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSuggestedOutfitsPrompt',
  input: {schema: AiSuggestedOutfitsInputSchema},
  output: {schema: AiSuggestedOutfitsOutputSchema},
  prompt: `You are a personal stylist for SJ Boots & Hats, an online e-commerce website. A user is currently viewing a particular product. Based on the description of this product, suggest a hat and boots that would complement it. Return your answer as a JSON object.

Product Description: {{{productDescription}}}

Here's an example of the output format:
{
  "hatSuggestion": "a wide-brimmed felt hat",
    "bootsSuggestion": "classic cowboy boots"
}
`,
});

const aiSuggestedOutfitsFlow = ai.defineFlow(
  {
    name: 'aiSuggestedOutfitsFlow',
    inputSchema: AiSuggestedOutfitsInputSchema,
    outputSchema: AiSuggestedOutfitsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
